# General Information
name: Brora Rangers Football Club
short_name: Brora Rangers
description: The Official Brora Rangers Football Club Website.
email: brorarangersfc@highlandleague.com
website: http://brorarangers.football

#Google Drive Sheet location
fixtures: 'https://docs.google.com/spreadsheets/d/1Fxm6FxSu4W6wZfIfiO8vd5xKN-MybdTFDFmwHRnO-QM/edit#gid=0' #Google sheet with fixtures and results list
squad: 'https://docs.google.com/spreadsheets/d/1Fxm6FxSu4W6wZfIfiO8vd5xKN-MybdTFDFmwHRnO-QM/edit#gid=172930968' #Google sheet with 1st team squad and stats
merchandise: 'https://docs.google.com/spreadsheets/d/15HVLZswEFfENyOsV9NUDD6y7oMTWVYtBFa_0KGtd_9Q/edit#gid=0' #Google merchandise sheet

#Google API
api: AIzaSyBVDGAYElUnb2L7RQNM5NjnClnUkw6eZsU

twitter: brorarangers #don't include @ symbol
twitter-hashtag: COYR #don't include # symbol
facebook:
club_badge: /images/badge.png

# Pricing info
season_ticket: £135.00
gold_card: £250.00
hospitality: £80.00
player_sponsor: £150.00
supporters_club: £20.00


# Website Configuration

primary_team_colour: red
secondary_team_colour: white

sass:
    style: :compressed

paginate: 20
paginate_path: "/archives/page:num/"

future: true
