# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brora Rangers Football Club
web-email: brorarangers@gmail.com
club-email: brorarangersfc@highlandleague.com
description: "Welcome to the Digital Dudgeon Park. All the news, views, reports and previews from Brora Rangers, Sutherland's Scottish Highland Football League Club"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brorarangers.football" # the base hostname & protocol for your site
twitter_username:
github_username:
repository: brorarangers/brorarangers.github.io
# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
future: true
include: [_pages]
exclude: [package.json, node_modules, Gemfile, Gemfile.lock, README.md, gulpfile.js]

gems:
  - jekyll-feed
  - jekyll-paginate

collections:
  previews:
    output: true
    permalink: /:year/:month/:day/:title/
  reports:
    output: true
    permalink: /:year/:month/:day/:title/
  people:
    output: true
  chairmans-chat:
    output: true
    permalink: /:year/:month/:day/:title/
  lotto:
    output: false

paginate: 15
paginate_path: "/archive/page:num/"
#### Site settings ####
current-season: 2017


## Prose stuff
prose:
  rooturl: "_chairmans-chat"
